Test branch
alimulondo/stack-version pull request #3
Opened 2018-08-18 15:18 UTC by alimulondo

What does this PR do?

This PR Implements the test cases of the api.

Description of Task to be completed?
View questions endpoint tested
Answer to question tested
View single question tested

.

2018-08-20 05:54 UTC, hadijahkyampeire approved these changes
LGTM

2018-08-20 13:30 UTC, JoyLubega requested changes

2018-08-20 13:30 UTC, JoyLubega commented on tests/Test_base.py
> +        self.assertEqual(result.status_code, 200)
Avoiding testing for status codes only. Test for data

2018-08-20 13:32 UTC, JoyLubega requested changes
Make your Readme detailed, its should include project setup

2018-08-22 00:37 UTC, alimulondo commented
I have effected the changes

2018-08-24 12:57 UTC, merged

2018-08-24 12:58 UTC, alimulondo commented
Challenge two completed